### ISSUE TITLE
Strange bush shows up on mp/ctf3 in the base.

### ISSUE THREAD

**Issue by ensiform** [xycaleth/OpenJK#14]
Rend2:
![shot2014-03-30_23-03-38](https://cloud.githubusercontent.com/assets/997399/2575685/d9a4b8c2-b958-11e3-89cc-40f47bab5995.png)

Vanilla:
![shot2014-03-31_13-31-30](https://cloud.githubusercontent.com/assets/997399/2575686/dece3616-b958-11e3-81dd-4c72c197f143.png)

**Comment by DT85** [comment]
That bush exists in the BSP file when viewed in Noesis, and there's a shadow on the ground for it in both images. This is a vanilla renderer bug, the model should be there.

**Comment by ensiform** [comment]
Lol so bug in basejka then?

**Comment by xycaleth** [comment]
Sounds like it

**Comment by ensiform** [comment]
Still looks bad though in the rend2.

**Comment by ensiform** [comment]
So was this figured out or just leaving it as is?
