### ISSUE TITLE
rend2: misc_model_static turn black 

### ISSUE THREAD

**Issue by DT85** [xycaleth/OpenJK#18]
misc_model_statics with a rend2 shader turn black when the player is in first person view, but isn't black in third person.

**Comment by xycaleth** [comment]
Wow, it's not just misc_model_statics that mess up. misc_models also don't look correct in first person!

**Comment by xycaleth** [comment]
Should be fixed in c59e7050.

@DT85 Could you just double check it's actually fixed the thing you mentioned? :)

**Comment by DT85** [comment]
Looks fixed to me, nice work. :dancer:
