### ISSUE TITLE
Rend2: Dark shaded triangles on player models

### ISSUE THREAD

**Issue by DT85** [xycaleth/OpenJK#20]
Dark shaded triangles on player models that are randomised. Sometimes they show, sometimes they don't.

**Comment by xycaleth** [comment]
Not sure how I'm going to fix this one. I'm unable to reproduce the same issue with my AMD card :( As far as I know, it's only happening on Nvidia cards.

**Comment by DT85** [comment]
And it looks to only happen on ghoul2 models. MD3 is unaffected.

**Comment by xycaleth** [comment]
Fixed in 7289d015. Silly mistake :p
