### ISSUE TITLE
Depth issue on some maps you mentioned having not found the cause yet 

### ISSUE THREAD

**Issue by ensiform** [xycaleth/OpenJK#42]
![shot2016-04-25_12-20-57](https://cloud.githubusercontent.com/assets/997399/14829403/c83ef4e2-0bb0-11e6-8dd8-c5f06ec931ee.png)

![shot2016-04-25_12-21-20](https://cloud.githubusercontent.com/assets/997399/14829407/cb5503c4-0bb0-11e6-91f3-db3895f843dd.png)

**Comment by xycaleth** [comment]
I think this should be fixed by a5a26728?

**Comment by ensiform** [comment]
Not yet fixed

**Comment by xycaleth** [comment]
Possibly fixed in c2c2c2a?

**Comment by xycaleth** [comment]
Maybe fixed in 4babf973 now?

**Comment by ensiform** [comment]
Not fixed.

**Comment by ensiform** [comment]
The issue is actually related to the sky apparently as r_fastsky 1 makes the issue it go away.

**Comment by ensiform** [comment]
What did you find for the cause?  You mentioned a possible solution last night.

**Comment by xycaleth** [comment]
Fixed in 60d8e94f.
