### ISSUE TITLE
Disintegration effect

### ISSUE THREAD

**Issue by xycaleth** [xycaleth/OpenJK#43]
The disintegration effect which comes from a disruptor alt fire needs to be implemented for feature parity with the vanilla renderer.

**Comment by ensiform** [comment]
Pretty sure it's **_Dis_**integration.  And there are two flavors.

**Comment by xycaleth** [comment]
Heh not sure how I typod that :p

**Comment by xycaleth** [comment]
Fixed in a2e0b54
