### ISSUE TITLE
Viewmodel Sticks in wall when up close

### ISSUE THREAD

**Issue by ensiform** [xycaleth/OpenJK#50]
In vanilla renderer, the model never sticks into the wall.  In rend2 this currently appears to always happen.

Vanilla:
![shot2016-05-02_22-17-55](https://cloud.githubusercontent.com/assets/997399/14973903/d56f0b7c-10b3-11e6-966d-e69666e9e7dd.png)

Rend2:
![shot2016-05-02_22-18-13](https://cloud.githubusercontent.com/assets/997399/14973905/dd08b9e6-10b3-11e6-848d-5f815f2ef460.png)

**Comment by Razish** [comment]
related: `RF_NODEPTH` and other known depth issues. viewmodels are rendered without depth testing

**Comment by xycaleth** [comment]
Fixed in c2c2c2

**Comment by xycaleth** [comment]
Eh, maybe not fixed :(

**Comment by xycaleth** [comment]
Fixed in 4babf973?

**Comment by ensiform** [comment]
Feexed.
